Shoppy/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('products.urls', namespace='products')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth import views as auth_views


urlpatterns =  [
	#url(r'^$', views.hola_mundo, name='hola'),
	url(r'^login/$', views.auth_login, name='Logueo'),
	url(r'^logout$', auth_views.logout, {'next_page': '/'} , name='logout'),
	url(r'^$', views.Productolista.as_view(), name='hola'),
	url(r'^productos/(?P<pk>[0-9]+)/$', views.Detallesproductos.as_view(), name='detalle'),
	url(r'^productos/nuevo/', views.producto_nuevo, name='nuevo'),
	url(r'^productos/tabla/', views.productstables, name='tabla'),
]

clients/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.


class Client(models.Model):
	nombre = models.CharField(max_length=100)
	telefono = models.IntegerField(unique=True)
	email = models.EmailField(max_length=255)
	domicilio = models.CharField(max_length=100)

	def __str__(self):
		return self.nombre

	class Meta:
		ordering=('nombre',)

login/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

products/models.py
from __future__ import unicode_literals

from django.db import models
from clients.models import Client

# Create your models here.


class Product(models.Model):
	
	producto = models.CharField(max_length=255)
	descripcion = models.CharField(max_length=255)
	categoria = models.CharField(max_length=255)
	precio = models.DecimalField(max_digits=15, decimal_places=2)
	imagen = models.ImageField(blank=True)

	def __str__(self):
		return self.producto


	class Meta: 
		ordering=('id',)


class Favorito(models.Model):
	user = models.ForeignKey(Client)
	product = models.ForeignKey(Product)

	class Meta:
		verbose_name = 'Favoritos'
		verbose_name_plural = 'Favoritos'

	def __str__(self):
		return '%s %s' % (self.user.nombre, self.product.descripcion)

products/forms.py
from django import forms
from .models import Product



class Productoform(forms.ModelForm):
	class Meta:
		model = Product
		fields = '__all__'

clients/views.py
from django.shortcuts import render

# Create your views here.

login/views.py
from django.shortcuts import render

# Create your views here.

products/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import (
	render, 
	get_object_or_404,
	redirect
)

from django.shortcuts import loader

from django.views.generic import ListView
from django.views.generic.detail import DetailView
#para el logueo y deslogueo del sistema
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User
#para el formulario de alta y los modelos de tabla
from .models import Product
from .forms import Productoform
#para la vista de table2
from .tables import ProductsTable
from django_tables2 import RequestConfig






# Create your views here.

# def hola_mundo(request):
# 	product = Product.objects.order_by('producto')
# 	template = loader.get_template('index.html')
# 	context = {
# 		'productos':product
# 	}	
# 	return HttpResponse(template.render(context, request))
# 	#return render(request, 'index.html')



# def productodetalle(request, pk):
# 	producto = get_object_or_404(Product, pk=pk)
# 	template = loader.get_template('productodetail.html')
# 	context = {
# 		'product': producto
# 	}
# 	return HttpResponse(template.render(context, request))


class Productolista(ListView):
	model = Product


class Detallesproductos(DetailView):
	model = Product
		

def producto_nuevo(request):
	formulario = Productoform(request.POST, request.FILES)
	if request.method == "POST":
		if formulario.is_valid():
			product = formulario.save(commit=False)
			product.save()
			return HttpResponseRedirect('/')
	else:
		form = Productoform()

	template = loader.get_template('new_product.html')
	context = {
		'form' : formulario
		}
	return HttpResponse(template.render(context, request))


def auth_login(request):
	if request.method == "POST":
		action = request.POST.get('action', None)
		username = request.POST.get('username', None)
		password = request.POST.get('password', None)


		if action == 'signup':
			user = User.objects.create_user(username=username,
										password=password)
			user.save()

		if action == 'login':
			user = authenticate(username=username, password=password)
			login(request, user)
			return redirect('/')
	
	context={}
	return render(request, 'login/login.html', context)


def productstables(request):
	productos = Product.objects.all()
	tabla = ProductsTable(productos)
	RequestConfig(request).configure(tabla)

	return render(request, 'products_tables.html', 
		{'productstables': tabla})

templates/index.html
<html>

<head>
	{% load staticfiles %}
	<meta charset="UTF-8">
	<title>document</title>
	<link rel="stylesheet" href="{% static 'css/base.css' %}">
</head>
<body>
	<a href="{% url 'products:nuevo'%}">Nuevo Producto</a>
	<ul>
	{% for pr in object_list %}
	<li>
		<a href="{% url 'products:detalle' pr.id %}">
		{{ pr.producto }}
		</a>
		{{ pr.precio }} <br>
		<img src="{{ pr.imagen.url }}" alt="">
	</li>
	{% endfor %}
	</ul>	
</body>
</html>

templates/login/login.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Login</title>
</head>
<body>
	<h1>Login<h1>
	<form action="" method="POST">
		{% csrf_token %}
		<input type="hidden" name="action" value="login">

		<input type="text" name="username">
		<input type="text" name="password">

		<input type="submit" value="Loguear">
	</form>
	<h2>darse de alta</h2>
	<form action="" method="POST">
		{% csrf_token %}
		<input type="hidden" name="action" value="signup">

		<input type="text" name="username">
		<input type="text" name="password">

		<input type="submit" value="Guardar">
	</form>
</body>
</html>

templates/new_product.html
<html lang="es">
<head>
	{% load staticfiles %}
	<meta charset="UTF-8">
	<title>Producto Nuevo</title>
	<link rel="stylesheet" href="{% static 'css/base.css' %}">
</head>
<body>
	<h1>Producto Nuevo</h1>
	<form method="POST" enctype="multipart/form-data">
		{% csrf_token %}
		{{ form.as_p}}
		<button type="submit">enviar</button>
	</form>
</body>
</html>

templates/productodetail.html
<!DOCTYPE html>
<html lang="es">
<head>
	{% load staticfiles %}
	<meta charset="UTF-8">
	<title>{{ product.producto }}</title>
	<link rel="stylesheet" href="{% static 'css/base.css' %}">
</head>
<body>
	<h1>{{ product.producto }}</h1>
	<h2>{{ product.descripcion }}</h2>
	<p>{{ product.precio }}</p>
	<img src="{{ product.imagen.url }}" alt="">
	
</body>
</html>

templates/products/product_detail.html
<!DOCTYPE html>
<html lang="es">
<head>
	{% load staticfiles %}
	<meta charset="UTF-8">
	<title>{{ product.producto }}</title>
	<link rel="stylesheet" href="{% static 'css/base.css' %}">
</head>
<body>
	<h1>{{ product.producto }}</h1>
	<h2>{{ product.descripcion }}</h2>
	<p>{{ product.precio }}</p>
	<img src="{{ product.imagen.url }}" alt="">
	
</body>
</html>

templates/products/product_list.html
<html>

<head>
	{% load staticfiles %}
	<meta charset="UTF-8">
	<title>Lista de Productos</title>
	<h1>Lista de Productos</h1>
	<link rel="stylesheet" href="{% static 'css/base.css' %}" rel="stylesheet">
</head>
<body>
	<h1>
		{% if user.is_authenticated %}
			<h3>{{ user.username }} | <a href="{% url 'products:logout' %}">Cerrar sesión></a>
		{% else %}
			<h3><a href="{% url 'products:Logueo' %}">Iniciar sesion</a>
		{% endif %}
	</h1>

	<br>
	<br>
	<br>
	<a href="{% url 'products:nuevo'%}">Nuevo Producto</a>
	<br>
	<a href="{% url 'products:tabla' %}">Mostrar en tabla el listado</a>
	<br>
	<br>
	{% for pr in object_list %}
	<table>
		<tr> 	
			<th>Detalle del Producto</th>
			<th>Precio</th>
			<th>Foto/Imagen<th>
		</tr>
		<tr>
			<td>
			<a href="{% url 'products:detalle' pr.id %}"> {{pr.producto }}</a></td>
			<td>
			{{ pr.precio }}</td>
			<td>
				<img src="{{ pr.imagen.url }}" alt="">
			</td>
		</tr>
	</table>
	
	{% endfor %}
	</ul>	
</body>
</html>

templates/products/products_tables.html
<!DOCTYPE html>
<html lang="en">
<head>
	{% load static %}
	{% load render_table from django_tables2 %}
	<meta charset="UTF-8">
	<title>Productos por tablas</title>
	<link rel="stylesheet" href="{% static 'css/base.css' %}" rel="stylesheet">
</head>
<body>
	<h1>Listado de Productos con el complemento TABLE2-2</h1>
	<div class="table">
		{% render_table productstables2 %}
	</div>
</body>
</html>

templates/products_tables.html
{% load render_table from django_tables2 %}
{% load static %}
<!DOCTYPE html>
<link rel="stylesheet" type="text/css" href="base.css">
<html lang="en">
<head>

	<meta charset="UTF-8">
	<title>Productos por tablas</title>
</head>
<body>
	<h1>Listado de Productos con el complemento TABLE2</h1>
	<div class="table">
	{% render_table productstables %}
	</div>
</body>
</html>